### PR TITLE
Give useful error when EMSCRIPTEN is not set

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by sbc100** [comment]
I'm still seing a link failure: `emcc: error: emcc: cannot find library "SDL_image"`

How did that work previously?

**Comment by kripken** [comment]
I think we may need to remove `-lSDL_image` in the makefile here. But maybe we should fix emcc to ignore that?

**Comment by kripken** [comment]
(it worked on fastcomp somehow in the past, but I think we made `-lX` stricter at some point)

**Comment by sbc100** [comment]
I see.. I had no idea that `emmake` did that.  I guess this change is not needed after all. 

Instead perhaps lets give a error saying "please run with emmake" if EMSCRIPTEN is not found?

However emmake is designed to override CC and CXX etc... its designed for makefiles that are not necarrily aware of emscripten at all right?   At keast it seens like setting CXX = emcc is redundant when using emmake.

I can't see any change what would have allowed `-lSDL_image` with fastcomp.   I agree we should accept it if we used to..  we should look into how that ever works,

**Comment by kripken** [comment]
> However emmake is designed to override CC and CXX etc... its designed for makefiles that are not necarrily aware of emscripten at all right? 

Correct, yeah. But it also sets `EMSCRIPTEN` which can be useful too, even if not the main intended goal.

**Comment by kripken** [comment]
Overall though, I don't have a clear idea in my head of the "right" way to do this. Maybe using EMSCRIPTEN is wrong. I trust your views on this type of thing more than my own.

**Comment by sbc100** [comment]
OK.. I think this is better PTAL.

**Comment by sbc100** [comment]
Can you land?  I don't have write access here.

**Pull request merged**
